#ifndef CONFIGPACKNAMEENUM_HPP
#define CONFIGPACKNAMEENUM_HPP

enum ConfigPackName{
  GENERAL_CONFIG,
  PROJECTS,
  OTHER_PROJECTS,
  NUMB_OF_CONFIG_PACK_NAME
};

#endif // CONFIGPACKNAMEENUM_HPP
