#ifndef FLANGEMATERIALSFILEPARAMS_HPP
#define FLANGEMATERIALSFILEPARAMS_HPP

enum FlangeMaterialsFileParams{
    FLANGE_NAME,
    FLANGE_LINEAR_EXPANSTION,
    FLANGE_FIDUCIAL_TEMP,
    NUMB_OF_FLANGE_MATERIALS_FILE_PARAMS
};

#endif // FLANGEMATERIALSFILEPARAMS_HPP
