#ifndef GENERALPARAMNAMES_HPP
#define GENERALPARAMNAMES_HPP

enum GeneralParamNames{
  DEFAULT_PATH,
  AUTOCAD_PATH,
  NUMB_OF_PROJ,
  NUMB_OF_REC,
  SORTING_TYPE,
  NUMB_OF_GENERAL_PARAM_NAMES
};

#endif // GENERALPARAMNAMES_HPP
