#ifndef INNERWINSTATUSCEPENUM_HPP
#define INNERWINSTATUSCEPENUM_HPP
enum InnerWinStatusCEP{
    CHOOSE_PROJECT_CEP,
    FLANGE,
    PIPE,
    FLOW,
    FLUID,
    RESULT
};
#endif // INNERWINSTATUSCEPENUM_HPP
