#ifndef INNERWINSTATUSCPENUM_HPP
#define INNERWINSTATUSCPENUM_HPP
enum InnerWinStatusCP{
    CHOOSE_PROJECT_INNER,
    NEW_PROJECT,
    OPEN_PROJECT,
    DELETE_PROJECT
};
#endif // INNERWINSTATUSCPENUM_HPP
