#ifndef MATERIALSCHANGESWIDGETSTATSENUM_HPP
#define MATERIALSCHANGESWIDGETSTATSENUM_HPP

enum MaterialsChangesWidgetStats{
    CHOOSING,
    ADD,
    REMOVE,
    EDIT
};

#endif // MATERIALSCHANGESWIDGETSTATSENUM_HPP
