#ifndef MATERIALSCHANGESWIDGETTYPEENUM_HPP
#define MATERIALSCHANGESWIDGETTYPEENUM_HPP

enum MaterialsChangesWidgetType{
    FLANGE_MATERIAL_TYPE,
    PIPE_MATERIAL_TYPE,
    SUBSTANCE_TYPE
};

#endif // MATERIALSCHANGESWIDGETTYPEENUM_HPP
