#ifndef PIPEMATERIALSFILEPARAMS_HPP
#define PIPEMATERIALSFILEPARAMS_HPP

enum PipeMaterialsFileParams{
    PIPE_NAME,
    PIPE_LINEAR_EXPANSTION,
    PIPE_FIDUCIAL_TEMP,
    NUMB_OF_PIPE_MATERIALS_FILE_PARAMS
};

#endif // PIPEMATERIALSFILEPARAMS_HPP
